config/routes.rb
Transport::Application.routes.draw do
  resources :destinations

  resources :boats
  root :to => "boats#index"
  
  match "/sitemap.:format" => "boats#sitemap"
     

end

app/models/boat.rb
class Boat < ActiveRecord::Base
  attr_accessible :id,:activated, :berths, :cabins, :description, :fuel_capacity, :heads, :hull, :length_ft, :max_persons, :model_name, :model_year, :name, :permalink, :water_capacity
  
  before_create :generate_unique_permlink
  
  self.primary_key = "permalink"
  
  def generate_unique_permlink
  	# p self.name
  	# p self.model_name
  	# p self.model_year
  	# p "=-===========0=0=0"
  	self.permalink = Base64.encode64(self.name+self.model_name+self.model_year.to_s+rand(1000..10000).to_s)
  end
end

app/models/destination.rb
class Destination < ActiveRecord::Base
  attr_accessible :activated, :introduction, :name, :permalink, :starting_price, :tagline, :weather_high, :weather_low, :weather_months, :weather_temperature
  
  before_create :generate_unique_permlink
  
    self.primary_key = "permalink"

  def generate_unique_permlink
  
  	self.permalink = ActiveSupport::Base64.encode64(self.name+self.tagline+rand(1000..10000).to_s)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  # GET /boats
  # GET /boats.json
  def index
  	@page = 1
  	@offset = 0
  	@limit = 2
  	@len = Boat.all.length
  	if params[:offset]
  		@offset = params[:offset].to_i
  		@page = ((@offset+1.0) /(@limit)).ceil
  	end
    @boats = Boat.all.slice(@offset,@limit)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boats }
    end
  end

  # GET /boats/1
  # GET /boats/1.json
  def show
    # @boat = Boat.find_by_permalink(params[:permalink])
    @boat = Boat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @boat }
    end
  end

  # GET /boats/new
  # GET /boats/new.json
  def new
    @boat = Boat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @boat }
    end
  end

  # GET /boats/1/edit
  def edit
    @boat = Boat.find(params[:id])
  end

  # POST /boats
  # POST /boats.json
  def create
    @boat = Boat.new(params[:boat])
    respond_to do |format|
      if @boat.save
        format.html { redirect_to @boat, notice: 'Boat was successfully created.' }
        format.json { render json: @boat, status: :created, location: @boat }
      else
        format.html { render action: "new" }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boats/1
  # PUT /boats/1.json
  def update
    @boat = Boat.find(params[:id])

    respond_to do |format|
      if @boat.update_attributes(params[:boat])
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @boat = Boat.find(params[:id])
    @boat.destroy

    respond_to do |format|
      format.html { redirect_to boats_url }
      format.json { head :no_content }
    end
  end
  
  
  
  def sitemap
    
  end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  # GET /destinations
  # GET /destinations.json
  def index
  	@page = 1
  	@offset = 0
  	@limit = 2
  	@len = Destination.all.length
  	if params[:offset]
  		@offset = params[:offset].to_i
  		@page = ((@offset+1.0) /(@limit)).ceil
  	end
    @destinations = Destination.all.slice(@offset,@limit)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @destinations }
    end
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
    @destination = Destination.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @destination }
    end
  end

  # GET /destinations/new
  # GET /destinations/new.json
  def new
    @destination = Destination.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @destination }
    end
  end

  # GET /destinations/1/edit
  def edit
    @destination = Destination.find(params[:id])
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(params[:destination])

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render json: @destination, status: :created, location: @destination }
      else
        format.html { render action: "new" }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /destinations/1
  # PUT /destinations/1.json
  def update
    @destination = Destination.find(params[:id])

    respond_to do |format|
      if @destination.update_attributes(params[:destination])
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination = Destination.find(params[:id])
    @destination.destroy

    respond_to do |format|
      format.html { redirect_to destinations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/boats/_form.html.erb
<%= form_for(@boat) do |f| %>
  <% if @boat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boat.errors.count, "error") %> prohibited this boat from being saved:</h2>

      <ul>
      <% @boat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :model_name %><br />
    <%= f.text_field :model_name %>
  </div>
  <div class="field">
    <%= f.label :model_year %><br />
    <%= f.number_field :model_year %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :activated %><br />
    <%= f.number_field :activated %>
  </div>
  <div class="field">
    <%= f.label :hull %><br />
    <%= f.text_field :hull %>
  </div>
  <div class="field">
    <%= f.label :length_ft %><br />
    <%= f.number_field :length_ft %>
  </div>
  <div class="field">
    <%= f.label :cabins %><br />
    <%= f.number_field :cabins %>
  </div>
  <div class="field">
    <%= f.label :berths %><br />
    <%= f.number_field :berths %>
  </div>
  <div class="field">
    <%= f.label :heads %><br />
    <%= f.number_field :heads %>
  </div>
  <div class="field">
    <%= f.label :max_persons %><br />
    <%= f.number_field :max_persons %>
  </div>
  <div class="field">
    <%= f.label :fuel_capacity %><br />
    <%= f.number_field :fuel_capacity %>
  </div>
  <div class="field">
    <%= f.label :water_capacity %><br />
    <%= f.number_field :water_capacity %>
  </div>
 <!--  <div class="field">
    <%= f.label :permalink %><br />
    <%= f.text_field :permalink %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boats/edit.html.erb
<h1>Editing boat</h1>

<%= render 'form' %>

<%= link_to 'Show', @boat %> |
<%= link_to 'Back', boats_path %>

app/views/boats/index.html.erb
<h1>Listing boats</h1>

<table >
  <tr>
    <th>Name</th>
    <th>Model name</th>
    <th>Model year</th>
    <!-- <th>Description</th>
    <th>Activated</th>
    <th>Hull</th>
    <th>Length ft</th>
    <th>Cabins</th>
    <th>Berths</th>
    <th>Heads</th>
    <th>Max persons</th>
    <th>Fuel capacity</th>
    <th>Water capacity</th>
    <th>Permalink</th> -->
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @boats.each do |boat| %>
  <tr>
    <td><%= boat.name %></td>
    <td><%= boat.model_name %></td>
    <td><%= boat.model_year %></td>
    <!-- <td><%= boat.description %></td>
    <td><%= boat.activated %></td>
    <td><%= boat.hull %></td>
    <td><%= boat.length_ft %></td>
    <td><%= boat.cabins %></td>
    <td><%= boat.berths %></td>
    <td><%= boat.heads %></td>
    <td><%= boat.max_persons %></td>
    <td><%= boat.fuel_capacity %></td>
    <td><%= boat.water_capacity %></td>
    <td><%= boat.permalink %></td> -->
    <td><%= link_to 'Show', boat %></td>
    <td><%= link_to 'Edit', edit_boat_path(boat) %></td>
    <td><%= link_to 'Destroy', boat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%if @offset > 0%>
<%= link_to 'Previous', :controller=>"boats" ,:offset => (@offset - @limit) %>
<%end%>
<%if @len > @limit %>
&nbsp;&nbsp;&nbsp;
<%= @page%> / <%= (@len/(@limit+0.0)).ceil%>
&nbsp;&nbsp;&nbsp;
<%end%>
<%if @offset+@limit < @len%>
<%= link_to 'Next', :controller=>"boats"  ,:offset => (@offset+@limit) %>
<%end%>
<br />
<br />

<%= link_to 'New Boat', new_boat_path %>

app/views/boats/new.html.erb
<h1>New boat</h1>

<%= render 'form' %>

<%= link_to 'Back', boats_path %>

app/views/boats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @boat.name %>
</p>

<p>
  <b>Model name:</b>
  <%= @boat.model_name %>
</p>

<p>
  <b>Model year:</b>
  <%= @boat.model_year %>
</p>

<p>
  <b>Description:</b>
  <%= @boat.description %>
</p>

<p>
  <b>Activated:</b>
  <%= @boat.activated %>
</p>

<p>
  <b>Hull:</b>
  <%= @boat.hull %>
</p>

<p>
  <b>Length ft:</b>
  <%= @boat.length_ft %>
</p>

<p>
  <b>Cabins:</b>
  <%= @boat.cabins %>
</p>

<p>
  <b>Berths:</b>
  <%= @boat.berths %>
</p>

<p>
  <b>Heads:</b>
  <%= @boat.heads %>
</p>

<p>
  <b>Max persons:</b>
  <%= @boat.max_persons %>
</p>

<p>
  <b>Fuel capacity:</b>
  <%= @boat.fuel_capacity %>
</p>

<p>
  <b>Water capacity:</b>
  <%= @boat.water_capacity %>
</p>

<p>
  <b>Permalink:</b>
  <%= @boat.permalink %>
</p>


<%= link_to 'Edit', edit_boat_path(@boat) %> |
<%= link_to 'Back', boats_path %>

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :starting_price %><br />
    <%= f.number_field :starting_price %>
  </div>
  <div class="field">
    <%= f.label :tagline %><br />
    <%= f.text_field :tagline %>
  </div>
  <div class="field">
    <%= f.label :introduction %><br />
    <%= f.text_area :introduction %>
  </div>
  <div class="field">
    <%= f.label :weather_months %><br />
    <%= f.text_field :weather_months %>
  </div>
  <div class="field">
    <%= f.label :weather_temperature %><br />
    <%= f.number_field :weather_temperature %>
  </div>
  <div class="field">
    <%= f.label :weather_high %><br />
    <%= f.number_field :weather_high %>
  </div>
  <div class="field">
    <%= f.label :weather_low %><br />
    <%= f.number_field :weather_low %>
  </div>
  <div class="field">
    <%= f.label :activated %><br />
    <%= f.number_field :activated %>
  </div>
  <!-- <div class="field">
    <%= f.label :permalink %><br />
    <%= f.text_field :permalink %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<h1>Listing destinations</h1>

<table >
  <tr>
    <th>Name</th>
    <th>Starting price</th>
    <th>Tagline</th>
    <!-- <th>Introduction</th>
    <th>Weather months</th>
    <th>Weather temperature</th>
    <th>Weather high</th>
    <th>Weather low</th>
    <th>Activated</th>
    <th>Permalink</th> -->
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @destinations.each do |destination| %>
  <tr>
    <td><%= destination.name %></td>
    <td><%= destination.starting_price %></td>
    <td><%= destination.tagline %></td>
    <!-- <td><%= destination.introduction %></td>
    <td><%= destination.weather_months %></td>
    <td><%= destination.weather_temperature %></td>
    <td><%= destination.weather_high %></td>
    <td><%= destination.weather_low %></td>
    <td><%= destination.activated %></td>
    <td><%= destination.permalink %></td> -->
    <td><%= link_to 'Show', destination %></td>
    <td><%= link_to 'Edit', edit_destination_path(destination) %></td>
    <td><%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%if @offset > 0%>
<%= link_to 'Previous', :controller=>"destinations" ,:offset => (@offset - @limit) %>
<%end%>
<%if @len > @limit %>
&nbsp;&nbsp;&nbsp;
<%= @page%> / <%= (@len/(@limit+0.0)).ceil%>
&nbsp;&nbsp;&nbsp;
<%end%>

<%if @offset+@limit < @len%>
<%= link_to 'Next', :controller=>"destinations"  ,:offset => (@offset+@limit) %>
<%end%>
<br />
<br />


<%= link_to 'New Destination', new_destination_path %>

app/views/destinations/new.html.erb
<h1>New destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @destination.name %>
</p>

<p>
  <b>Starting price:</b>
  <%= @destination.starting_price %>
</p>

<p>
  <b>Tagline:</b>
  <%= @destination.tagline %>
</p>

<p>
  <b>Introduction:</b>
  <%= @destination.introduction %>
</p>

<p>
  <b>Weather months:</b>
  <%= @destination.weather_months %>
</p>

<p>
  <b>Weather temperature:</b>
  <%= @destination.weather_temperature %>
</p>

<p>
  <b>Weather high:</b>
  <%= @destination.weather_high %>
</p>

<p>
  <b>Weather low:</b>
  <%= @destination.weather_low %>
</p>

<p>
  <b>Activated:</b>
  <%= @destination.activated %>
</p>

<p>
  <b>Permalink:</b>
  <%= @destination.permalink %>
</p>


<%= link_to 'Edit', edit_destination_path(@destination) %> |
<%= link_to 'Back', destinations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Transport</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <center>
      <h2> <%= link_to 'Boats', boats_path %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to 'Destinations', destinations_path %> 
      </h2>
      <br />
      <%= yield %>
    </center>
  </body>
</html>